### Send to local a valid Zipcode POST request with json body
GET http://localhost:8080
Content-Type: application/json

{
  "zipcode": "21930190"
}

### Send to localhost an invalid Zipcode POST request with json body
GET http://localhost:8080
Content-Type: application/json

{
  "zipcode": "999999"
}

### Send to CloudRun a valid Zipcode POST request with json body
GET http://localhost:8080
Content-Type: application/json

{
  "zipcode": "21930190"
}

### Send to CloudRun an invalid Zipcode POST request with json body
GET http://localhost:8080
Content-Type: application/json

{
  "zipcode": "999999"
}